server:
  port: 8082
spring:
  name: tariffs-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5555/tariffs}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
tariffs-service:
  client:
    products-service-url: ${PRODUCTS_SERVICE_PATH:http://localhost:8081}